/*
FILE: BuiltInRegistration.h
PRIMARY AUTHOR: Kieran Williams

Copyright � 2017 DigiPen (USA) Corporation.
*/

// This file will eventually be autogenerated.

#include "BuiltInRegistration.h"

using namespace ::meta;

namespace meta
{
	void Init()
	{
		BuiltInRegistration::Meta__Register__BuiltInRegistration();
	}
}
