/*
FILE: Registration.cpp
PRIMARY AUTHOR: Kiera Williams

Just includes an autogenerated file.

Copyright (c) 2017 DigiPen (USA) Corporation.
*/

#include "__AutogeneratedRegistration.meta"
